"use client";
import React from 'react';
import { InlineMediaField, SingleMediaUpload } from './[id]/MediaUploader';

type Props={tab:string;config:any;websiteId:string;onChange:(config:any)=>void};
const set=(cfg:any,path:string[],value:any)=>{const n=structuredClone(cfg);let cur=n;for(let i=0;i<path.length-1;i++){if(!cur[path[i]]||typeof cur[path[i]]!=='object')cur[path[i]]={};cur=cur[path[i]];}cur[path[path.length-1]]=value;return n;};
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="builder-field"><span>{label}</span>{children}</label>}
function Switch({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className={`builder-toggle ${value?'on':''}`}><span><b>{label}</b><small>{value?'Enabled':'Disabled'}</small></span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/></label>}
function ArrayEditor({items,onChange,kind,websiteId}:{items:any[];onChange:(v:any[])=>void;kind:'reason'|'photo'|'video'|'audio';websiteId:string}){
  const add=()=>{const base=kind==='reason'?{text:'New reason',emoji:'✨'}:kind==='photo'?{url:'',title:'New memory',caption:'',date:'',alt:''}:kind==='video'?{url:'',title:'New video',caption:'',poster:'',alt:''}:{id:String(Date.now()),title:'New track',url:'',type:'auto',enabled:true};onChange([...items,base]);};
  const move=(i:number,d:number)=>{const a=items.slice(),j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];onChange(a)};
  return <div className="builder-list-editor"><div className="builder-item-list" style={{display:'flex',flexDirection:'column',gap:12}}>{items.map((it,i)=><div key={it.id||i} className="builder-item builder-item-card" style={{display:'flex',flexDirection:'column',gap:8,alignItems:'stretch'}}>
    <div className="builder-item-card-head"><span className="builder-item-card-num">{kind==='reason'?'Reason':kind==='photo'?'Memory':kind==='video'?'Video':'Track'} {i+1}</span><div className="builder-reorder"><button type="button" onClick={()=>move(i,-1)} disabled={i===0}>↑</button><button type="button" onClick={()=>move(i,1)} disabled={i===items.length-1}>↓</button></div></div>
    {kind==='reason'&&<><Field label="Emoji"><input value={it.emoji||''} onChange={e=>onChange(items.map((x,k)=>k===i?{...x,emoji:e.target.value}:x))}/></Field><Field label="Reason"><textarea rows={3} value={it.text||''} onChange={e=>onChange(items.map((x,k)=>k===i?{...x,text:e.target.value}:x))}/></Field></>}
    {kind==='photo'&&<><Field label="Photo"><InlineMediaField value={it.url||''} onChange={v=>onChange(items.map((x,k)=>k===i?{...x,url:v}:x))} placeholder="Public image URL" accept="image/*" folder="gallery" websiteId={websiteId}/></Field><div className="builder-grid-2"><Field label="Title"><input value={it.title||''} onChange={e=>onChange(items.map((x,k)=>k===i?{...x,title:e.target.value}:x))}/></Field><Field label="Date / label"><input value={it.date||''} onChange={e=>onChange(items.map((x,k)=>k===i?{...x,date:e.target.value}:x))}/></Field></div><Field label="Caption"><textarea rows={2} value={it.caption||''} onChange={e=>onChange(items.map((x,k)=>k===i?{...x,caption:e.target.value}:x))}/></Field><Field label="Alt text"><input value={it.alt||''} onChange={e=>onChange(items.map((x,k)=>k===i?{...x,alt:e.target.value}:x))}/></Field></>}
    {kind==='video'&&<><Field label="Video"><InlineMediaField value={it.url||''} onChange={v=>onChange(items.map((x,k)=>k===i?{...x,url:v}:x))} placeholder="Direct MP4 / YouTube URL" accept="video/*" folder="video" websiteId={websiteId}/></Field><Field label="Thumbnail / poster"><InlineMediaField value={it.poster||''} onChange={v=>onChange(items.map((x,k)=>k===i?{...x,poster:v}:x))} placeholder="Public poster URL" accept="image/*" folder="video-posters" websiteId={websiteId}/></Field><Field label="Title"><input value={it.title||''} onChange={e=>onChange(items.map((x,k)=>k===i?{...x,title:e.target.value}:x))}/></Field><Field label="Caption"><textarea rows={2} value={it.caption||''} onChange={e=>onChange(items.map((x,k)=>k===i?{...x,caption:e.target.value}:x))}/></Field><Field label="Alt text"><input value={it.alt||''} onChange={e=>onChange(items.map((x,k)=>k===i?{...x,alt:e.target.value}:x))}/></Field></>}
    {kind==='audio'&&<><Field label="Audio / YouTube / Spotify"><InlineMediaField value={it.url||''} onChange={v=>onChange(items.map((x,k)=>k===i?{...x,url:v}:x))} placeholder="MP3, YouTube, Spotify or playlist URL" accept="audio/*" folder="music" websiteId={websiteId}/></Field><Field label="Title"><input value={it.title||''} onChange={e=>onChange(items.map((x,k)=>k===i?{...x,title:e.target.value}:x))}/></Field><Switch label="Enabled" value={it.enabled!==false} onChange={v=>onChange(items.map((x,k)=>k===i?{...x,enabled:v}:x))}/></>}
    <div style={{display:'flex',gap:8}}><button type="button" className="builder-mini-btn" onClick={()=>onChange(items.filter((_,k)=>k!==i))}>Delete</button>{kind!=='reason'&&<button type="button" className="builder-mini-btn" onClick={()=>onChange([...items.slice(0,i+1),{...it,id:it.id?String(it.id)+'-copy-'+Date.now():undefined},...items.slice(i+1)])}>Duplicate</button>}</div>
  </div>)}</div><button type="button" className="builder-mini-btn mt-3" onClick={add}>+ Add {kind==='reason'?'Reason':kind==='photo'?'Memory':kind==='video'?'Video':'Track'}</button></div>
}
function TextArrayEditor({items,onChange}:{items:string[];onChange:(v:string[])=>void}){
  const move=(i:number,d:number)=>{const a=items.slice(),j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];onChange(a)};
  return <div className="builder-list-editor"><div className="builder-item-list" style={{display:'flex',flexDirection:'column',gap:12}}>{items.map((item,i)=><div key={i} className="builder-item builder-item-card"><div className="builder-item-card-head"><span className="builder-item-card-num">Paragraph {i+1}</span><div className="builder-reorder"><button type="button" onClick={()=>move(i,-1)} disabled={i===0}>↑</button><button type="button" onClick={()=>move(i,1)} disabled={i===items.length-1}>↓</button></div></div><textarea rows={4} value={item} onChange={e=>onChange(items.map((x,k)=>k===i?e.target.value:x))}/><button type="button" className="builder-mini-btn" onClick={()=>onChange(items.filter((_,k)=>k!==i))}>Delete</button></div>)}</div><button type="button" className="builder-mini-btn mt-3" onClick={()=>onChange([...items,'New paragraph'])}>+ Add Paragraph</button></div>
}
export default function MasterBirthdayEditor({tab,config,websiteId,onChange}:Props){
  const c=config; const patch=(p:string[],v:any)=>onChange(set(c,p,v));
  if(tab==='overview') return <><Section title="Master Birthday basics"><div className="builder-grid-2"><Field label="Recipient name"><input value={c.recipientName||''} onChange={e=>patch(['recipientName'],e.target.value)}/></Field><Field label="Sender name"><input value={c.senderName||''} onChange={e=>patch(['senderName'],e.target.value)}/></Field><Field label="Age"><input type="number" min={1} value={c.age||1} onChange={e=>patch(['age'],Number(e.target.value))}/></Field><Field label="Birthday date"><input type="date" value={c.birthdayDate||''} onChange={e=>patch(['birthdayDate'],e.target.value)}/></Field><Field label="Birthday time"><input type="time" value={c.birthdayTime||'00:00'} onChange={e=>patch(['birthdayTime'],e.target.value)}/></Field><Field label="Timezone"><input value={c.timezone||''} placeholder="Asia/Dhaka" onChange={e=>patch(['timezone'],e.target.value)}/></Field><Field label="Page title"><input value={c.pageTitle||''} onChange={e=>patch(['pageTitle'],e.target.value)}/></Field><Field label="Browser title"><input value={c.browserTitle||''} onChange={e=>patch(['browserTitle'],e.target.value)}/></Field></div></Section><Section title="Secret section"><div className="builder-grid-2"><Field label="Secret image"><InlineMediaField value={c.secret.imageUrl||''} onChange={v=>patch(['secret','imageUrl'],v)} placeholder="Public image URL" accept="image/*" folder="gallery" websiteId={websiteId}/></Field><Field label="Button text"><input value={c.secret.buttonText||''} onChange={e=>patch(['secret','buttonText'],e.target.value)}/></Field><Field label="Button icon"><input value={c.secret.buttonIcon||''} onChange={e=>patch(['secret','buttonIcon'],e.target.value)}/></Field><Field label="Social platform"><select value={c.secret.socialPlatform||'instagram'} onChange={e=>patch(['secret','socialPlatform'],e.target.value)}><option value="instagram">Instagram</option><option value="facebook">Facebook</option><option value="x">X</option><option value="tiktok">TikTok</option><option value="custom">Custom</option></select></Field><Field label="Social URL"><input type="url" value={c.secret.socialUrl||''} onChange={e=>patch(['secret','socialUrl'],e.target.value)}/></Field></div></Section></>;
  if(tab==='opening') return <><Section title="Countdown"><div className="builder-grid-2"><Field label="Countdown title"><input value={c.countdownTitle||''} onChange={e=>patch(['countdownTitle'],e.target.value)}/></Field><Field label="Countdown message"><textarea rows={3} value={c.countdownMessage||''} onChange={e=>patch(['countdownMessage'],e.target.value)}/></Field><Field label="Countdown audio"><InlineMediaField value={c.countdownAudioUrl||''} onChange={v=>onChange(set(c,['countdownAudioUrl'],v))} placeholder="Public audio URL" accept="audio/*" folder="music" websiteId={websiteId}/></Field><Switch label="Audio enabled" value={c.countdownAudioEnabled!==false} onChange={v=>patch(['countdownAudioEnabled'],v)}/></div></Section><Section title="Greeting"><div className="builder-grid-2"><Field label="Greeting heading"><input value={c.greetingHeading||''} onChange={e=>patch(['greetingHeading'],e.target.value)}/></Field><Field label="Greeting message"><textarea rows={3} value={c.greetingMessage||''} onChange={e=>patch(['greetingMessage'],e.target.value)}/></Field><Field label="Enter button text"><input value={c.enterButtonText||''} onChange={e=>patch(['enterButtonText'],e.target.value)}/></Field></div></Section></>;
  if(tab==='story') return <><Section title="Cake"><div className="builder-grid-2"><Field label="Cake text"><input value={c.cake.cakeText||''} onChange={e=>patch(['cake','cakeText'],e.target.value)}/></Field><Field label="Birthday text"><input value={c.cake.birthdayText||''} onChange={e=>patch(['cake','birthdayText'],e.target.value)}/></Field><Field label="Recipient name"><input value={c.cake.recipientName||''} onChange={e=>patch(['cake','recipientName'],e.target.value)}/></Field><Field label="Age / candle count"><input type="number" min={1} value={c.cake.age||1} onChange={e=>patch(['cake','age'],Number(e.target.value))}/></Field><Field label="Wish title"><input value={c.cake.wishTitle||''} onChange={e=>patch(['cake','wishTitle'],e.target.value)}/></Field><Field label="Wish subtitle"><input value={c.cake.wishSubtitle||''} onChange={e=>patch(['cake','wishSubtitle'],e.target.value)}/></Field><Field label="Mic hint"><input value={c.cake.micHint||''} onChange={e=>patch(['cake','micHint'],e.target.value)}/></Field><Field label="Cake status"><input value={c.cake.cakeStatus||''} onChange={e=>patch(['cake','cakeStatus'],e.target.value)}/></Field><Field label="Cut instruction"><input value={c.cake.cutInstruction||''} onChange={e=>patch(['cake','cutInstruction'],e.target.value)}/></Field><Field label="Next button text"><input value={c.cake.nextButtonText||''} onChange={e=>patch(['cake','nextButtonText'],e.target.value)}/></Field></div><div className="builder-toggle-grid"><Switch label="Microphone" value={c.cake.microphone!==false} onChange={v=>patch(['cake','microphone'],v)}/><Switch label="Sound effects" value={c.cake.soundEffects!==false} onChange={v=>patch(['cake','soundEffects'],v)}/><Switch label="Vibration" value={c.cake.vibration!==false} onChange={v=>patch(['cake','vibration'],v)}/></div></Section><Section title="Reasons"><ArrayEditor items={c.reasons||[]} onChange={v=>patch(['reasons'],v)} kind="reason" websiteId={websiteId}/></Section></>;
  if(tab==='gallery') return <Section title="Photo / Memory gallery"><p className="text-sm text-slate-500 mb-4">Original photos stay as defaults. Add, edit, delete, duplicate and reorder. Lightbox uses the same collection automatically.</p><ArrayEditor items={c.gallery||[]} onChange={v=>patch(['gallery'],v)} kind="photo" websiteId={websiteId}/></Section>;
  if(tab==='video') return <Section title="Video collection"><ArrayEditor items={c.videos||[]} onChange={v=>patch(['videos'],v)} kind="video" websiteId={websiteId}/></Section>;
  if(tab==='music') return <><Section title="Our Soundtrack"><p className="text-sm text-slate-500 mb-4">Add audio files, direct public audio URLs, YouTube links/playlists or Spotify tracks/playlists. The template chooses the first enabled track for its original soundtrack slot.</p><ArrayEditor items={c.soundtrack||[]} onChange={v=>patch(['soundtrack'],v)} kind="audio" websiteId={websiteId}/></Section></>;
  if(tab==='letter') return <Section title="Letter"><div className="builder-grid-2"><Field label="Letter title"><input value={c.letter.title||''} onChange={e=>patch(['letter','title'],e.target.value)}/></Field><Field label="Signature"><input value={c.letter.signature||''} onChange={e=>patch(['letter','signature'],e.target.value)}/></Field><Field label="Button text"><input value={c.letter.buttonText||''} onChange={e=>patch(['letter','buttonText'],e.target.value)}/></Field></div><TextArrayEditor items={c.letter.paragraphs||[]} onChange={v=>patch(['letter','paragraphs'],v)}/></Section>;
  if(tab==='theme') return <Section title="Visual customization"><div className="builder-grid-2"><Field label="Main theme color"><input type="color" value={c.visual.mainThemeColor||'#ff69b4'} onChange={e=>patch(['visual','mainThemeColor'],e.target.value)}/></Field><Field label="Secondary color"><input type="color" value={c.visual.secondaryColor||'#9370db'} onChange={e=>patch(['visual','secondaryColor'],e.target.value)}/></Field><Field label="Accent color"><input type="color" value={c.visual.accentColor||'#9b6dff'} onChange={e=>patch(['visual','accentColor'],e.target.value)}/></Field><Field label="Button color"><input type="color" value={c.visual.buttonColor||'#ff69b4'} onChange={e=>patch(['visual','buttonColor'],e.target.value)}/></Field><Field label="Text color"><input type="color" value={c.visual.textColor||'#4a4a4a'} onChange={e=>patch(['visual','textColor'],e.target.value)}/></Field><Field label="Glow color"><input type="color" value={c.visual.glowColor||'#ff69b4'} onChange={e=>patch(['visual','glowColor'],e.target.value)}/></Field><Field label="Background overlay"><input value={c.visual.backgroundOverlay||''} onChange={e=>patch(['visual','backgroundOverlay'],e.target.value)}/></Field><Field label="Background image"><InlineMediaField value={c.visual.backgroundImage||''} onChange={v=>patch(['visual','backgroundImage'],v)} placeholder="Public image URL" accept="image/*" folder="backgrounds" websiteId={websiteId}/></Field><Field label="Background video"><InlineMediaField value={c.visual.backgroundVideo||''} onChange={v=>patch(['visual','backgroundVideo'],v)} placeholder="Public video URL" accept="video/*" folder="backgrounds" websiteId={websiteId}/></Field><Field label="Light / Dark mode"><select value={c.visual.mode||'light'} onChange={e=>patch(['visual','mode'],e.target.value)}><option value="light">Light</option><option value="dark">Dark</option></select></Field><Field label="Font preset"><select value={c.visual.font||'Quicksand'} onChange={e=>patch(['visual','font'],e.target.value)}><option>Quicksand</option><option>Dancing Script</option><option>Bubblegum Sans</option><option>Comic Neue</option><option>Caveat</option></select></Field></div></Section>;
  if(tab==='effects') return <Section title="Effects"><div className="builder-toggle-grid">{Object.entries(c.visual.effects||{}).map(([k,v])=><Switch key={k} label={k.replace(/([A-Z])/g,' $1')} value={!!v} onChange={x=>patch(['visual','effects',k],x)}/>)}</div></Section>;
  return null;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="builder-section"><div className="builder-section-head"><div><h2>{title}</h2></div></div><div className="mt-5">{children}</div></section>}
